version: '3.4'

services:
  timeseriespoc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Timescale=Server=database;Port=5432;Database=time-series;User Id=admin;Password=password;Include Error Detail=true;
      - OpenSearchNode=https://opensearch.greenmotion.tech
    ports:
      - "8080"
