# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: PostgreSQL
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: PostgreSQL
  uid: PBFA97CFB590B2093
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: database:5432
  # <string> database password, if used
  password: password
  # <string> database user, if used
  user: admin
  # <string> database name, if used
  database: ""
  # <bool> enable/disable basic auth
  basicAuth: false
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     connMaxLifetime: 14400
     database: "time-series"
     maxIdleConns: 100
     maxIdleConnsAuto: true
     maxOpenConns: 100
     postgresVersion: 1400
     sslmode: "disable"
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true