{
 "title": "Charging Session",
 "time": { "from": "2023-12-19T06:08:29.226Z", "to": "2023-12-19T11:05:50.156Z" },
 "templating": {
  "list": [
   {
    "name": "ChargerId",
    "query": "SELECT distinct chargerid FROM public.sample"
   },
   {
    "name": "TransactionId",
    "query": "SELECT distinct transactionid FROM public.sample WHERE chargerid='$ChargerId'"
   },
   { "name": "interval", "query": "1m,5m,10m,30s" }
  ]
 },
 "panels": [
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH cte AS(\r\n\tSELECT\r\n\tavg(value::double precision) as value,\r\n\ttime_bucket('$interval', timestamp) as \"time\" \r\n\tFROM sample \r\n\tWHERE chargerid = '$ChargerId' AND transactionid = '$TransactionId' AND $__timeFilter(timestamp) AND measurand = 'Energy.Active.Import.Register' \r\n\tGROUP BY time\r\n\tORDER BY time\r\n)\r\nSELECT\r\ntime, \r\n(\r\n    CASE\r\n      WHEN value >= lag(value) OVER w\r\n        THEN value - lag(value) OVER w\r\n      WHEN lag(value) OVER w IS NULL THEN 0\r\n      ELSE value\r\n    END\r\n  ) AS energy\r\nFROM CTE\r\nWINDOW w AS (ORDER BY time)\r\nORDER BY time;"
    },
    {
     "rawSql": "WITH first_value AS (\r\n\tSELECT first((value::double precision),timestamp) as value\r\n\tFROM sample\r\n\tWHERE chargerid = '$ChargerId' AND transactionid = '$TransactionId' AND measurand = 'Energy.Active.Import.Register' \r\n)\r\nSELECT \r\n(avg(s.value::double precision) - fv.value)/1000.0 as TotalEnergy,\r\ntime_bucket('$interval', s.timestamp) as \"time\" \r\nFROM sample s\r\nCROSS JOIN first_value fv\r\nWHERE chargerid = '$ChargerId' AND transactionid = '$TransactionId' AND $__timeFilter(timestamp) AND measurand = 'Energy.Active.Import.Register' \r\nGROUP BY time, fv.value\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Power vs Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\navg(value::double precision) AS voltage, \r\ntime_bucket('$interval', timestamp) as \"time\" \r\nFROM sample \r\nWHERE chargerid = '$ChargerId' AND transactionid = '$TransactionId' AND $__timeFilter(timestamp) AND measurand = 'Voltage' \r\nGROUP BY time\r\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT \r\navg(value::double precision)/1000.0 AS \"power\", \r\ntime_bucket('1m', timestamp) as \"time\" \r\nFROM sample \r\nWHERE chargerid = '$ChargerId' AND transactionid = '$TransactionId' AND $__timeFilter(timestamp) AND measurand = 'Power.Active.Import' \r\nGROUP BY time\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\navg(value::double precision) AS L1, \r\ntime_bucket('$interval', timestamp) as \"time\" \r\nFROM sample \r\nWHERE \r\nchargerid = '$ChargerId' AND \r\ntransactionid = '$TransactionId' AND \r\n$__timeFilter(timestamp) AND \r\nmeasurand = 'Current.Import' AND \r\nphase = 'L1' \r\nGROUP BY time\r\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT \r\navg(value::double precision) AS L2,\r\ntime_bucket('$interval', timestamp) as \"time\" \r\nFROM sample \r\nWHERE \r\nchargerid = '$ChargerId' AND \r\ntransactionid = '$TransactionId' AND \r\n$__timeFilter(timestamp) AND \r\nmeasurand = 'Current.Import' AND \r\nphase = 'L2'\r\nGROUP BY time\r\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT \r\navg(value::double precision) AS L3, \r\ntime_bucket('$interval', timestamp) as \"time\" \r\nFROM sample \r\nWHERE \r\nchargerid = '$ChargerId' AND \r\ntransactionid = '$TransactionId' AND \r\n$__timeFilter(timestamp) AND \r\nmeasurand = 'Current.Import' AND \r\nphase = 'L3'\r\nGROUP BY time\r\nORDER BY time ASC"
    }
   ]
  }
 ]
}